[package]
name = "moonwave_resources"
version = "0.1.0"
authors = ["Rene Eichhorn <rene.eichhorn1@gmail.com>"]
edition = "2018"

[dependencies]
parking_lot = "0.11"
slotmap = "1.0"
bitflags = "1.2"
wgpu = "0.8"
optick = "1.3"
